# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_dist <- function(x, dist_method = 1L) {
    .Call(`_RcppHelp_rcpp_dist`, x, dist_method)
}

rcpp_algo <- function(x, dist) {
    .Call(`_RcppHelp_rcpp_algo`, x, dist)
}

rcppParAlgo <- function(x) {
    .Call(`_RcppHelp_rcppParAlgo`, x)
}

